name: "release"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: gitconfig
        run: |
          git config user.name "mziglioli"
          git config user.email "marcelozigliolil@gmail.com"
      - name: install
        run: npm intall
      - name: publish
        run: npm config set '//npm.pkg.github.com/:_authToken' "${NPM_TOKEN}" && npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
