name: "release"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: publish
        run: yarn && yarn release
        env:
          GITHUB_TOKEN: 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
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
